import Link from 'next/link';

export const metadata = {
  title: "Terms of Service | Lucky Pick Canada",
};

export default function TermsOfService() {
  return (
    <main className="max-w-4xl mx-auto p-6 leading-relaxed">
      <div className="mb-6">
        <Link href="/" className="text-blue-600 hover:underline">
          &larr; Back to Home
        </Link>
      </div>
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">Last Updated: August 10, 2026</p>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-3">Use of Platform</h2>
        <p className="mb-4">
          Welcome to Lucky Pick Canada. Our platform is a digital random number generation and luck-themed digital card reveal service designed strictly for entertainment purposes. By accessing or using our website, you agree to these Terms of Service. If you do not agree with any part of these terms, please do not use our service.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-3">Premium Cards</h2>
        <p className="mb-4">
          Lucky Pick Canada offers specialized features, including the Coast to Coast premium card. Please note that access to these premium features is subject to platform availability. We reserve the right to modify, suspend, or discontinue any card concept, tier, or feature at any time without prior notice.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-3">Disclaimer</h2>
        <p className="mb-4">
          While we use advanced cryptographic algorithms for true randomness, the service is provided on an &quot;as is&quot; and &quot;as available&quot; basis. The results generated by our tool are purely for fun and entertainment. We do not accept liability for any decisions, friendly wagers, financial choices, or actions taken based on the results generated by Lucky Pick Canada. Use the platform responsibly.
        </p>
      </section>
    </main>
  );
}
